<?php
/**
 * Redirect default WordPress login page to the custom Elementor login page.
 */

/**
 * Redirects traffic from wp-login.php to the custom login page (/login/).
 */
function custom_redirect_wp_login_to_elementor_page() {
    // Get the URL of your custom Elementor login page (it's /login/)
    $custom_login_url = home_url( '/login/' );

    // Check if the user is trying to access wp-login.php
    // and is not performing specific actions like logging out or posting a password
    if (
        'wp-login.php' === $GLOBALS['pagenow'] &&
        ! is_admin() && // Ensure this doesn't interfere with admin-ajax etc.
        ! isset( $_GET['action'] ) &&
        $_GET['action'] !== 'logout' &&
        $_GET['action'] !== 'postpass' // Allow access for password protected posts
    ) {
        // Redirect to the custom login page
        wp_safe_redirect( $custom_login_url );
        exit; // Always exit after a redirect
    }
}
// Hook this function early, before headers are sent. 'init' is suitable.
// A priority less than 10 is sometimes recommended to run before other plugins.
add_action( 'init', 'custom_redirect_wp_login_to_elementor_page', 5 );


/**
 * Filters the login URL generated by wp_login_url() and related functions
 * to point to your custom Elementor login page (/login/).
 *
 * @param string $login_url    The default login URL (wp-login.php).
 * @param string $redirect     The redirect URL parameter, if provided.
 * @return string The filtered login URL pointing to your custom page.
 */
function custom_filter_login_url_to_elementor_page( $login_url, $redirect ) {
    // Get the URL of your custom Elementor login page
    $custom_login_url = home_url( '/login/' );

    // Append the redirect parameter if it exists (important for functionality)
    if ( ! empty( $redirect ) ) {
        $custom_login_url = add_query_arg( 'redirect_to', urlencode( $redirect ), $custom_login_url );
    }

    return $custom_login_url;
}
// Hook into the 'login_url' filter. Priority 10 is standard.
add_filter( 'login_url', 'custom_filter_login_url_to_elementor_page', 10, 2 );
?>