<?php
/**
 * Simple Custom Login Form Shortcode
 *
 * Provides a [custom_login_form] shortcode that displays a basic WordPress login form.
 * This version removes all redirection logic.
 *
 * @package CustomRegistrationLogin
 */

// Ensure this file is not accessed directly
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

/**
 * Renders a simple custom login form using the [custom_login_form] shortcode.
 *
 * This version does not include any redirection logic based on user roles
 * or login status. It simply displays the standard WordPress login form
 * generated by wp_login_form().
 *
 * @param array $atts Shortcode attributes (not used in this implementation).
 * @return string HTML for the login form.
 */
function custom_render_simple_login_form_shortcode( $atts ) {
    // Start output buffering to capture the HTML.
    ob_start();
    ?>
    <p><?php esc_html_e( 'Please log in.', 'customregistrationlogin' ); ?></p>
    <form id="custom-login-form" class="custom-login-form" method="post" action="<?php echo esc_url( site_url( 'wp-login.php', 'login_post' ) ); ?>">

        <?php
        // Important: Add a hidden redirect_to field. This tells wp-login.php where
        // to send the user after a successful login attempt. Defaulting to homepage.
        ?>
         <input type="hidden" name="redirect_to" value="<?php echo esc_url( home_url( '/' ) ); ?>" />


        <label for="user_login"><?php esc_html_e( 'Email or username', 'customregistrationlogin' ); ?><br />
        <input type="text" name="log" id="user_login" class="form-control input-text username-field" value="<?php echo esc_attr( isset( $_POST['log'] ) ? wp_unslash( $_POST['log'] ) : '' ); ?>" size="20" autocapitalize="off" /></label>

        <label for="user_pass"><?php esc_html_e( 'Password', 'customregistrationlogin' ); ?><br />
        <input type="password" name="pwd" id="user_pass" class="form-control input-text password-field" value="" size="20" /></label>

        <p class="forgetmenot">
            <label for="rememberme">
                <input name="rememberme" type="checkbox" id="rememberme" class="form-check-input" value="forever" /> <?php esc_html_e( 'Remember Me', 'customregistrationlogin' ); ?>
            </label>
        </p>

        <input type="submit" name="wp-submit" id="wp-submit" class="btn btn-primary login-button" value="<?php esc_attr_e( 'Log In', 'customregistrationlogin' ); ?>" />
         <?php // Include a hidden field for the test cookie - standard for wp-login.php ?>
         <input type="hidden" name="testcookie" value="1" />

         <?php
            // Add login error messages if any
            $errors = apply_filters( 'login_errors', '' ); // Filter login errors
            if ( ! empty( $errors ) ) {
                echo '<div class="login-error-message">' . $errors . '</div>';
            } elseif ( isset( $_GET['login'] ) && 'failed' === $_GET['login'] ) {
                 // Basic failure message if no specific error filter output (less common now with filters)
                 echo '<div class="login-error-message">' . esc_html__( 'Login failed. Please try again.', 'customregistrationlogin' ) . '</div>';
            }
         ?>

    </form>
    <p class="register-links">
        <?php
        // Prepare URLs and translatable text segments for the registration links
        $register_user_url = home_url( '/register' ); // Use home_url() for site-relative links
        $register_vendor_url = home_url( '/register-vendor' ); // Use home_url() for site-relative links

        $no_account_text = esc_html__( 'No account?', 'customregistrationlogin' );
        $register_user_text = esc_html__( 'Register as a user', 'customregistrationlogin' );
        $or_text = esc_html__( 'or', 'customregistrationlogin' ); // Comma is structural, "or" is translatable
        $register_vendor_text = esc_html__( 'register as a vendor', 'customregistrationlogin' );

        // Output the HTML structure with translated text and escaped URLs
        // This maintains the exact structure: "Text <a...>text</a>, text <a...>text</a>"
        echo $no_account_text . ' <a href="' . esc_url( $register_user_url ) . '">' . $register_user_text . '</a>, ' . $or_text . ' <a href="' . esc_url( $register_vendor_url ) . '">' . $register_vendor_text . '</a>';
        ?>
    </p>
    <?php
    // Return the buffered content.
    $output = ob_get_clean();
    return $output;
}

// Register the custom login form shortcode.
add_shortcode( 'custom_login_form', 'custom_render_simple_login_form_shortcode' );
?>
